### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yimingtan96** [UoA-eResearch/leapmotion_gestures#12]
Hi!

I'm currently trying to run "exploration-many2one.ipynb" on my own. May I know where I can find the file: 'data/recordings/normalization_data.csv' ?

I can't seem to find the exact file on the google drive link provided too.

Any help is much appreciated!

Thank you!

**Comment by aleathwick** [comment]
I suggest you read: https://github.com/UoA-eResearch/leapmotion_gestures#drop-unwanted-variables---standardize-variables

If you read the description of the code block that uses that file, you will see its purpose is to 'update the dictionaries used for normalizing and centering variables'. If you introduce a new variable, then you need to run this code to populate the dictionaries with values for those variables, so that values can be normalized/centered. You can use a csv of training data, and replace 'data/recordings/normalization_data.csv' with the path to that file.

Have you introduced new variables that don't have info in params/means_dict.json and params/stds_dict.json? If not, you don't need to run that block of code.

**Comment by yimingtan96** [comment]
> I suggest you read: https://github.com/UoA-eResearch/leapmotion_gestures#drop-unwanted-variables---standardize-variables
> 
> If you read the description of the code block that uses that file, you will see its purpose is to 'update the dictionaries used for normalizing and centering variables'. If you introduce a new variable, then you need to run this code to populate the dictionaries with values for those variables, so that values can be normalized/centered. You can use a csv of training data, and replace 'data/recordings/normalization_data.csv' with the path to that file.
> 
> Have you introduced new variables that don't have info in params/means_dict.json and params/stds_dict.json? If not, you don't need to run that block of code.

Got it, thank you!

I have yet to introduce new variables at the moment but will do so once I get a deeper understanding of how it works.
