### ISSUE TITLE
Question: Evaluate model training progress and accuracy

### ISSUE THREAD

**Issue by yimingtan96** [UoA-eResearch/leapmotion_gestures#14]
Hi there,

I'm trying to run the cells relating to the evaluation of the model in the "exploration-many2one" notebook and I would like to know how the original file "cputest-maxed.csv" was computed, or what kind of data/format needs to be in the CSV file? If you could kindly point me to the "cputest-maxed.csv" file, it would be helpful to me too.

I tried recording a set of gestures using record.py and I used that to test the model but there were several "A value is trying to be set on a copy of a slice from a DataFrame" warnings and "ValueError: Error when checking input: expected input_1 to have shape (10, 50) but got array with shape (40, 50)" errors that were returned.

I hope that I'm doing it correctly. My apologies, I'm trying to gain a deeper understanding of deep learning and I'm quite new to model training.

May I know what steps could be taken to resolve these issues?

**Comment by aleathwick** [comment]
cputest-maxed.csv was a file of leap motion data collected while cpu was at 100% usage. I was checking how cpu load affected the frame rate of collected data, and how that, in turn, could affect the accuracy of a model. That was just a one off thing, you can use any csv of collected data.

The ValueError is due to a mismatch between the data you're giving the model, and data the model is expecting. Data of shape (40, 50) has 40 observations (or 'frames'), with 50 variables, but the model is only expecting 10 observations (shape (10, 50)). That is because in the code block for generating data to train the model n_frames=10 is used, but in the later code block for generating test data n_frames is set to 40.

The first warning might not be an issue. After fixing the second ValueError, do things work?

**Comment by yimingtan96** [comment]
Hi,

Alright, I understand. 

Yeap, I've amended the number of frames and it works now. Thank you very much for your help and explanation!
