### ISSUE TITLE
Question: Training model using data of only one hand in frame

### ISSUE THREAD

**Issue by yimingtan96** [UoA-eResearch/leapmotion_gestures#16]
Hi,

May I know if it's possible to train a model using gestures with only one hand in the frame?
Would you kindly point me to the functions that I should look at?

Thank you

**Comment by aleathwick** [comment]
Hi, sorry I didn't get back to you on this in a timely fashion.

There is an argument `hands` for many of the functions responsible for parsing data, which is a list of the hands that functions should get data for. By default `hands` is `['left', 'right']`, but you could select one of those only. 

If you use `data.folder2examples()` to generate training data, and pass it `hands = ['left']`, then things should just work - any right hand data will be ignored, and any variables depending on the right hand or both hands will not be calculated.

If you have any issues getting that working, please let me know.

**Comment by yimingtan96** [comment]
Hi @aleathwick, no worries, thank you for getting back to me.

Yeap, I tried to just pass `hands = ['right']` initially but it reported that there were missing variables. I then realized it was because `mirror = True` and my right-handed variables were flipped. Once I set it to `mirror = False`, it worked perfectly. 

Thank you!

**Comment by aleathwick** [comment]
Thanks for pointing that out. To avoid this problem I've made a change so that `mirror = True` won't have any effect (instead producing a warning) if just one hand is passed in as an argument. That's the simple way of fixing it, ideally the one handed case should be handled with mirroring also, so that RH data can be used to train a LH model and vice versa.
